apiVersion: iam.hsdp.m.crossplane.io/v1
kind: Device
metadata:
  name: example-device
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  forProvider:
    loginID: example-device-01
    passwordSecretRef:
      name: example-device-password
      namespace: crossplane-system
      key: password
    deviceExtIdSystem: urn:hsdp:device
    deviceExtIdValue: example-device-01
    type: Mobile
    globalReferenceID: example-device-01
    organizationRef:
      name: example-org
    applicationRef:
      name: example-application
