apiVersion: iam.hsdp.m.crossplane.io/v1
kind: EmailTemplate
metadata:
  name: example-emailtemplate
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  forProvider:
    type: ACCOUNT_VERIFICATION
    managingOrganizationRef:
      name: example-org
    format: HTML
    locale: en-US
    subject: "Verify your account"
    from: noreply@example.com
    message: "<html><body>Please verify your account by clicking the link below.</body></html>"
    link: https://example.com/verify
