apiVersion: iam.hsdp.m.crossplane.io/v1
kind: Group
metadata:
  name: example-group
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  forProvider:
    name: example-group
    description: An example group
    managingOrganizationRef:
      name: example-org
