apiVersion: iam.hsdp.m.crossplane.io/v1
kind: Group
metadata:
  name: example-group
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  forProvider:
    name: example-group
    description: An example group
    managingOrganizationRef:
      name: example-org
    # roleRefs assigns each referenced Role's permissions to this Group's
    # members. Requires the referenced Role(s) to exist.
    roleRefs:
      - name: example-role
    # userRefs adds each referenced User as a member of this Group.
    userRefs:
      - name: example-user
    # serviceRefs adds each referenced Service as a member of this Group.
    serviceRefs:
      - name: example-service
    # deviceRefs adds each referenced Device as a member of this Group.
    deviceRefs:
      - name: example-device
