apiVersion: iam.hsdp.m.crossplane.io/v1
kind: PasswordPolicy
metadata:
  name: example-passwordpolicy
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  forProvider:
    managingOrganizationRef:
      name: example-org
    expiryPeriodInDays: 90
    historyCount: 5
    minLength: 12
    maxLength: 128
    minLowercase: 1
    minUppercase: 1
    minNumeric: 1
    minSpecialChars: 1
    challengesEnabled: true
    challengePolicy:
      defaultQuestions:
        - "What is your favorite color?"
        - "What is your pet's name?"
      minAnswerCount: 4
      minQuestionCount: 4
      maxIncorrectAttempts: 3
