apiVersion: iam.hsdp.m.crossplane.io/v1
kind: Proposition
metadata:
  name: example-proposition
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  forProvider:
    name: example-proposition
    description: An example proposition
    organizationRef:
      name: example-org
    globalReferenceId: example-proposition-global-id
