apiVersion: iam.hsdp.m.crossplane.io/v1
kind: Role
metadata:
  name: example-role
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  forProvider:
    name: example-role
    description: An example role with permissions
    managingOrganizationRef:
      name: example-org
    permissions:
      - PERMISSION_READ
      - PERMISSION_WRITE
    # sharingPolicies share this role's permissions with other
    # Organizations.
    sharingPolicies:
      - targetOrganizationRef:
          name: example-other-org
        sharingPolicy: ALL_USERS
        purpose: Cross-organization reporting access
