apiVersion: iam.hsdp.m.crossplane.io/v1
kind: Role
metadata:
  name: example-role
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: default
  forProvider:
    name: example-role
    description: An example role with permissions
    managingOrganizationRef:
      name: example-org
    permissions:
      - PERMISSION_READ
      - PERMISSION_WRITE
