//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSignature) DeepCopyInto(out *BootstrapSignature) {
	*out = *in
	out.PublicKeySecretRef = in.PublicKeySecretRef
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(BootstrapSignatureConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSignature.
func (in *BootstrapSignature) DeepCopy() *BootstrapSignature {
	if in == nil {
		return nil
	}
	out := new(BootstrapSignature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapSignatureConfig) DeepCopyInto(out *BootstrapSignatureConfig) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Padding != nil {
		in, out := &in.Padding, &out.Padding
		*out = new(string)
		**out = **in
	}
	if in.SaltLength != nil {
		in, out := &in.SaltLength, &out.SaltLength
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapSignatureConfig.
func (in *BootstrapSignatureConfig) DeepCopy() *BootstrapSignatureConfig {
	if in == nil {
		return nil
	}
	out := new(BootstrapSignatureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgConfiguration) DeepCopyInto(out *OrgConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgConfiguration.
func (in *OrgConfiguration) DeepCopy() *OrgConfiguration {
	if in == nil {
		return nil
	}
	out := new(OrgConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrgConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgConfigurationList) DeepCopyInto(out *OrgConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OrgConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgConfigurationList.
func (in *OrgConfigurationList) DeepCopy() *OrgConfigurationList {
	if in == nil {
		return nil
	}
	out := new(OrgConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrgConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgConfigurationObservation) DeepCopyInto(out *OrgConfigurationObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.VersionID != nil {
		in, out := &in.VersionID, &out.VersionID
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgConfigurationObservation.
func (in *OrgConfigurationObservation) DeepCopy() *OrgConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(OrgConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgConfigurationParameters) DeepCopyInto(out *OrgConfigurationParameters) {
	*out = *in
	out.ServiceAccount = in.ServiceAccount
	in.BootstrapSignature.DeepCopyInto(&out.BootstrapSignature)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgConfigurationParameters.
func (in *OrgConfigurationParameters) DeepCopy() *OrgConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(OrgConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgConfigurationSpec) DeepCopyInto(out *OrgConfigurationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgConfigurationSpec.
func (in *OrgConfigurationSpec) DeepCopy() *OrgConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(OrgConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgConfigurationStatus) DeepCopyInto(out *OrgConfigurationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgConfigurationStatus.
func (in *OrgConfigurationStatus) DeepCopy() *OrgConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(OrgConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccount) DeepCopyInto(out *ServiceAccount) {
	*out = *in
	out.ServiceAccountKeySecretRef = in.ServiceAccountKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccount.
func (in *ServiceAccount) DeepCopy() *ServiceAccount {
	if in == nil {
		return nil
	}
	out := new(ServiceAccount)
	in.DeepCopyInto(out)
	return out
}
