apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-hsdp
  annotations:
    meta.crossplane.io/maintainer: Andy Lo-A-Foe <andy.loafoe@gmail.com>
    meta.crossplane.io/source: github.com/loafoe/provider-hsdp
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      A native (non-upjet) Crossplane provider for the Philips DIP/HSDP
      platform, compatible with the legacy upjet-based provider-hsdp.
spec:
  capabilities:
    - safe-start
